version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www/
    volumes:
      - ..:/var/www
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ..:/var/www/
      - ./nginx:/etc/nginx/conf.d
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pandatest
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" 
      - "8025:8025" 

volumes:
  mysql_data:
    